version: '2'
services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: ./Dockerfile.api
        expose:
            - 8080
        ports:
            - 8080:8080            
        networks:
            - network

    ui:
        container_name: ui
        build:
            context: .
            dockerfile: ./Dockerfile.ui
        expose:
            - 4200
        ports:
            - 4200:4200
        networks:
            - network
        links:
            - api:api
        depends_on:
            - api

networks:
    network:
        driver: bridge


